# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
- env:
  - CGO_ENABLED=0

  binary: launch

  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

#release:
#  github:
#    owner: newclarity
#    name: launch
#
#  # IDs of the archives to use.
#  # Defaults to all.
#  ids:
#    # foo
#    # bar
#
#  # You can change the name of the GitLab release.
#  # Default is `{{.Tag}}`
#  # name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
#  name_template: "Release {{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
#
#  # You can disable this pipe in order to not upload any artifacts to
#  # GitLab.
#  # Defaults to false.
#  disable: true
#
#  # You can add extra pre-existing files to the release.
#  # The filename on the release will be the last part of the path (base). If
#  # another file with the same name exists, the latest one found will be used.
#  # Defaults to empty.
#  extra_files:
#    - glob: ./bin/*

