// Code generated by github.com/gearboxworks/buildtool DO NOT EDIT.

package main

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
	"PROFILE": reflect.ValueOf(&PROFILE),
}

var Consts = map[string]reflect.Value{
}

