// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package defaults

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
	"BinaryName": reflect.ValueOf(BinaryName),
	"BinaryRepo": reflect.ValueOf(BinaryRepo),
	"BinaryVersion": reflect.ValueOf(BinaryVersion),
	"BrandName": reflect.ValueOf(BrandName),
	"DefaultCommandName": reflect.ValueOf(DefaultCommandName),
	"DefaultPathCwd": reflect.ValueOf(DefaultPathCwd),
	"DefaultPathEmpty": reflect.ValueOf(DefaultPathEmpty),
	"DefaultPathHome": reflect.ValueOf(DefaultPathHome),
	"DefaultPathNone": reflect.ValueOf(DefaultPathNone),
	"DefaultProject": reflect.ValueOf(DefaultProject),
	"DefaultProvider": reflect.ValueOf(DefaultProvider),
	"DefaultUnitTestCmd": reflect.ValueOf(DefaultUnitTestCmd),
	"GearboxNetwork": reflect.ValueOf(GearboxNetwork),
	"LanguageAppName": reflect.ValueOf(LanguageAppName),
	"LanguageContainerName": reflect.ValueOf(LanguageContainerName),
	"LanguageContainerPluralName": reflect.ValueOf(LanguageContainerPluralName),
	"LanguageImageName": reflect.ValueOf(LanguageImageName),
	"LanguageImagePluralName": reflect.ValueOf(LanguageImagePluralName),
	"Organization": reflect.ValueOf(Organization),
	"SourceRepo": reflect.ValueOf(SourceRepo),
	"Timeout": reflect.ValueOf(Timeout),
}

