// Code generated by github.com/gearboxworks/buildtool DO NOT EDIT.

package defaults

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

