name: release

on:
  release:
    types: [published, edited]

jobs:
  build_docker_images:
    name: Building Images for ${{ github.ref }}
    strategy:
      matrix:
        versions: [all]
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: 00-env
      if: env.DOCKERHUB_TOKEN == ''
      run: exit 1
    - name: 01-pull
      id: pull
      uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: 02-list
      run: ls -l versions
    - name: 03-build
      # run: make ${{ steps.pull.args }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${SSH_KEY}"
        docker login --username gearboxbuild --password "${DOCKERHUB_TOKEN}"
        make release-${{ matrix.versions }}
